name: Deploy to Cloadflare R2
on:
  push:
    branches:
      - master
      - staging
      - develop
      - roslyn
  workflow_call:

jobs:
  build:
    name: Run Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      branch-postfix: ${{ github.ref_name }}
  deploy:
    name: Deploy to S3
    uses: OxideMod/Actions/.github/workflows/r2-publish.yaml@main
    needs: build
    with:
      generate-filehash: true
    secrets:
      CLOUDFLARE_R2_KEY: ${{ secrets.CLOUDFLARE_R2_KEY }}
      CLOUDFLARE_R2_SECRET: ${{ secrets.CLOUDFLARE_R2_SECRET }}
      CLOUDFLARE_R2_ENDPOINT: ${{ secrets.CLOUDFLARE_R2_ENDPOINT }}
